---
layout: post
title:  "Origins of the Yellow Fever Mosquito"
date:   2020-12-12 10:20:00
categories: research update
---
<img align="center" src="https://raw.githubusercontent.com/jsoghigian/jsoghigian.github.io/master/images/figure_summary.png" style="border:2px solid black;margin:5px 5px 5px 5px" height="575" width="700"> 
In a recent publication in Molecular Ecology, colleagues and I[^1] challenge traditional hypotheses on the origin of Ae. aegypti, arguably the world's deadliest disease vector.  The traditional story of this invasive mosquito's dispersal is relatively well known: We are pretty certain that the mosquito escaped Africa due to the slave trade in the 16th century, and subsequently spread across the globe in the 18th and 19th centuries, becoming firmly established on virtually every continent by the dawn of the 20th century.  Across its invasive range (and in some small populations in Africa), Ae. aegypti is anthrophilic and considered to be the subspeces Ae. aegypti aegypti; on continental Africa, the majority of populations are sylvan, with no preference for humans, and are considered to be the subspecies Ae. aegypti formosus.  And so, the story goes, this mosquito originated on continental Africa where it was a forest-dwelling, mammal-generalist, and somehow became adapted to humans much more recently.

Despite extensive knowledge of the genetics of this species across much of its invasive region, and renewed interest in the genetics in its native range, one part of the world has received comparatively little study: Madagascar and the islands in the southwestern Indian Ocean (SWIO - Panel A, below).  This biodiversity hotspot is home not only to Ae. aegypti, but the two species considered its nearest living relatives.  Moreover, it is also home to both subspecies of the mosquito.

Colleagues and I became curious about the importance of this region.  In preliminary analyses, we found something startling: Ae. aegypti populations on these islands appeared to diverge prior to those on continental Africa.  If true, this would imply that prior to becoming a globe trotter, this mosquito had been an island hopper - and had to be highly adaptable, given many of the islands in this region lacked mammals entirely until relatively recently!

And indeed, more detailed analyses did confirm these results: We found strong evidence through SNPs, microsatellites, and nucleotide sequence data that island populations of Ae. aegypti diverged prior to continental African populations.  We also found strong evidence of cryptic species on Madagascar!  Summarized in Panel B, above, our combined results suggest that an aegypti-like ancestor was circulating on these islands for tens of millions of years, before reaching Africa *far* more recently. Drilling down to the population level, in Panels C and D, we see that island populations diverged more recently.  Our analyses of microsatellites put the common ancestor of all African populations sometime less than 44,000 years ago, with the best-supported estimate at about 20,000 years ago - corresponding to changes in the climate of Africa due to deglaciation and a warming across the globe.  

This slight difference in perspective may suggest why it is that this mosquito has been so incredibly successful, while countless other very similar mosquitoes from Africa have not been.  These results suggest that Ae. aegypti on Africa could already have been quite adaptable.  After all, adaptation to island living - and island hopping - is no small feat, and there's certainly a different context to conquering the forests of a continent a few thousand years before spreading across the rest of the planet, rather than having been just another forest mosquito for millions of years.  

What might these results mean for public health, or vector competency? That's harder to say, particularly because we also found that the invasive - and highly competent - Ae. aegypti aegypti is interbreeding both with the sylvan Ae. a. formosus *and* its sister species on the islands.  Colleagues and I have applied for funding and hope to return to this region to understand how this admixture, as well as increasing contact between sylvan mosquitoes, humans, and livestock, will influence disease transmission in the region.
[^1]:Soghigian, J., Gloria-Soria, A., Robert, V., Le Goff, G., Failloux, A.B. and Powell, J.R., 2020. Genetic evidence for the origin of Aedes aegypti, the yellow fever mosquito, in the southwestern Indian Ocean. Molecular Ecology, 29(19), pp.3593-3606. (https://onlinelibrary.wiley.com/doi/full/10.1111/mec.15590)
